import { Component, inject, input } from '@angular/core';
import { TicketPantalla } from './ticket-pantalla/ticket-pantalla';
import { ComandasService } from '../../servicios/ComandasService';
import { ProductoMonitor } from '../../interfaces/productosenproduccion';
import { ComandaModel } from '../../interfaces/comanda';

@Component({
  selector: 'app-pantalla-comandas',
  imports: [TicketPantalla],
  templateUrl: './pantalla-comandas.html',
  styleUrl: './pantalla-comandas.css',
})
export class PantallaComandas {
  columnas = input(6);
  filas = input(1);

  srvComandas = inject(ComandasService);
  comandas = this.srvComandas.comandas;

  ngOnInit() {
    console.log('Cargando Registros');

    const dev: ProductoMonitor[] = [
      {
        descripcion: 'TARTAR DE ATÚN',
        idproducto: '01010',
        idmonitor: '01',
        folio: 1,
        movimiento: 1,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'SASHIMI DE ATUN ENTRADA',
        idproducto: '01043',
        idmonitor: '01',
        folio: 1,
        movimiento: 2,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'YAKUZA KOTEJI',
        idproducto: '01045',
        idmonitor: '01',
        folio: 1,
        movimiento: 3,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'YAKUZA OMAKASE',
        idproducto: '05003',
        idmonitor: '01',
        folio: 1,
        movimiento: 4,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'YAKUZA OMAKASE',
        idproducto: '05003',
        idmonitor: '01',
        folio: 1,
        movimiento: 5,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI CAMARON',
        idproducto: '07002',
        idmonitor: '01',
        folio: 1,
        movimiento: 6,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI ATUN',
        idproducto: '07003',
        idmonitor: '01',
        folio: 1,
        movimiento: 7,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI RIB EYE',
        idproducto: '07004',
        idmonitor: '01',
        folio: 1,
        movimiento: 8,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'EXPERIENCIA OMAKASE YAKUZA',
        idproducto: '08017',
        idmonitor: '01',
        folio: 1,
        movimiento: 9,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TARTAR DE ATÚN',
        idproducto: '01010',
        idmonitor: '01',
        folio: 2,
        movimiento: 1,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'SASHIMI DE ATUN ENTRADA',
        idproducto: '01043',
        idmonitor: '01',
        folio: 2,
        movimiento: 2,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'YAKUZA KOTEJI',
        idproducto: '01045',
        idmonitor: '01',
        folio: 2,
        movimiento: 3,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'YAKUZA OMAKASE',
        idproducto: '05003',
        idmonitor: '01',
        folio: 2,
        movimiento: 4,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'YAKUZA OMAKASE',
        idproducto: '05003',
        idmonitor: '01',
        folio: 2,
        movimiento: 5,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI CAMARON',
        idproducto: '07002',
        idmonitor: '01',
        folio: 2,
        movimiento: 6,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI ATUN',
        idproducto: '07003',
        idmonitor: '01',
        folio: 2,
        movimiento: 7,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI RIB EYE',
        idproducto: '07004',
        idmonitor: '01',
        folio: 2,
        movimiento: 8,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'EXPERIENCIA OMAKASE YAKUZA',
        idproducto: '08017',
        idmonitor: '01',
        folio: 2,
        movimiento: 9,
        cantidad: 1.0,
        comentario: 'Guarnicion extra',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'EXPERIENCIA OMAKASE YAKUZA',
        idproducto: '08017',
        idmonitor: '01',
        folio: 10,
        movimiento: 5,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TARTAR DE ATÚN',
        idproducto: '01010',
        idmonitor: '01',
        folio: 1,
        movimiento: 10,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'SASHIMI DE ATUN ENTRADA',
        idproducto: '01043',
        idmonitor: '01',
        folio: 1,
        movimiento: 11,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'YAKUZA KOTEJI',
        idproducto: '01045',
        idmonitor: '01',
        folio: 1,
        movimiento: 12,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'YAKUZA OMAKASE',
        idproducto: '05003',
        idmonitor: '01',
        folio: 1,
        movimiento: 13,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'YAKUZA OMAKASE',
        idproducto: '05003',
        idmonitor: '01',
        folio: 1,
        movimiento: 14,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI CAMARON',
        idproducto: '07002',
        idmonitor: '01',
        folio: 1,
        movimiento: 15,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI ATUN',
        idproducto: '07003',
        idmonitor: '01',
        folio: 1,
        movimiento: 16,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI RIB EYE',
        idproducto: '07004',
        idmonitor: '01',
        folio: 1,
        movimiento: 17,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'EXPERIENCIA OMAKASE YAKUZA',
        idproducto: '08017',
        idmonitor: '01',
        folio: 1,
        movimiento: 18,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TARTAR DE ATÚN',
        idproducto: '01010',
        idmonitor: '01',
        folio: 1,
        movimiento: 19,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'SASHIMI DE ATUN ENTRADA',
        idproducto: '01043',
        idmonitor: '01',
        folio: 1,
        movimiento: 20,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'YAKUZA KOTEJI',
        idproducto: '01045',
        idmonitor: '01',
        folio: 1,
        movimiento: 21,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'YAKUZA OMAKASE',
        idproducto: '05003',
        idmonitor: '01',
        folio: 1,
        movimiento: 22,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'YAKUZA OMAKASE',
        idproducto: '05003',
        idmonitor: '01',
        folio: 1,
        movimiento: 23,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI CAMARON',
        idproducto: '07002',
        idmonitor: '01',
        folio: 1,
        movimiento: 24,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI ATUN',
        idproducto: '07003',
        idmonitor: '01',
        folio: 1,
        movimiento: 25,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI RIB EYE',
        idproducto: '07004',
        idmonitor: '01',
        folio: 1,
        movimiento: 26,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'EXPERIENCIA OMAKASE YAKUZA',
        idproducto: '08017',
        idmonitor: '01',
        folio: 1,
        movimiento: 27,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TARTAR DE ATÚN',
        idproducto: '01010',
        idmonitor: '01',
        folio: 5,
        movimiento: 1,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'SASHIMI DE ATUN ENTRADA',
        idproducto: '01043',
        idmonitor: '01',
        folio: 5,
        movimiento: 2,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'YAKUZA KOTEJI',
        idproducto: '01045',
        idmonitor: '01',
        folio: 5,
        movimiento: 3,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'YAKUZA OMAKASE',
        idproducto: '05003',
        idmonitor: '01',
        folio: 5,
        movimiento: 4,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'YAKUZA OMAKASE',
        idproducto: '05003',
        idmonitor: '01',
        folio: 5,
        movimiento: 5,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI CAMARON',
        idproducto: '07002',
        idmonitor: '01',
        folio: 5,
        movimiento: 6,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI ATUN',
        idproducto: '07003',
        idmonitor: '01',
        folio: 5,
        movimiento: 7,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI RIB EYE',
        idproducto: '07004',
        idmonitor: '01',
        folio: 5,
        movimiento: 8,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'EXPERIENCIA OMAKASE YAKUZA',
        idproducto: '08017',
        idmonitor: '01',
        folio: 5,
        movimiento: 9,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TARTAR DE ATÚN',
        idproducto: '01010',
        idmonitor: '01',
        folio: 6,
        movimiento: 1,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'SASHIMI DE ATUN ENTRADA',
        idproducto: '01043',
        idmonitor: '01',
        folio: 6,
        movimiento: 2,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'YAKUZA KOTEJI',
        idproducto: '01045',
        idmonitor: '01',
        folio: 6,
        movimiento: 3,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'YAKUZA OMAKASE',
        idproducto: '05003',
        idmonitor: '01',
        folio: 6,
        movimiento: 4,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'YAKUZA OMAKASE',
        idproducto: '05003',
        idmonitor: '01',
        folio: 6,
        movimiento: 5,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI CAMARON',
        idproducto: '07002',
        idmonitor: '01',
        folio: 6,
        movimiento: 6,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI ATUN',
        idproducto: '07003',
        idmonitor: '01',
        folio: 6,
        movimiento: 7,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI RIB EYE',
        idproducto: '07004',
        idmonitor: '01',
        folio: 6,
        movimiento: 8,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'EXPERIENCIA OMAKASE YAKUZA',
        idproducto: '08017',
        idmonitor: '01',
        folio: 6,
        movimiento: 9,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TARTAR DE ATÚN',
        idproducto: '01010',
        idmonitor: '01',
        folio: 7,
        movimiento: 1,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'SASHIMI DE ATUN ENTRADA',
        idproducto: '01043',
        idmonitor: '01',
        folio: 7,
        movimiento: 2,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'YAKUZA KOTEJI',
        idproducto: '01045',
        idmonitor: '01',
        folio: 7,
        movimiento: 3,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'YAKUZA OMAKASE',
        idproducto: '05003',
        idmonitor: '01',
        folio: 7,
        movimiento: 4,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'YAKUZA OMAKASE',
        idproducto: '05003',
        idmonitor: '01',
        folio: 7,
        movimiento: 5,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI CAMARON',
        idproducto: '07002',
        idmonitor: '01',
        folio: 7,
        movimiento: 6,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI ATUN',
        idproducto: '07003',
        idmonitor: '01',
        folio: 7,
        movimiento: 7,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI RIB EYE',
        idproducto: '07004',
        idmonitor: '01',
        folio: 7,
        movimiento: 8,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'EXPERIENCIA OMAKASE YAKUZA',
        idproducto: '08017',
        idmonitor: '01',
        folio: 7,
        movimiento: 9,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TARTAR DE ATÚN',
        idproducto: '01010',
        idmonitor: '01',
        folio: 8,
        movimiento: 1,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'SASHIMI DE ATUN ENTRADA',
        idproducto: '01043',
        idmonitor: '01',
        folio: 8,
        movimiento: 2,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'YAKUZA KOTEJI',
        idproducto: '01045',
        idmonitor: '01',
        folio: 8,
        movimiento: 3,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'YAKUZA OMAKASE',
        idproducto: '05003',
        idmonitor: '01',
        folio: 8,
        movimiento: 4,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'YAKUZA OMAKASE',
        idproducto: '05003',
        idmonitor: '01',
        folio: 8,
        movimiento: 5,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI CAMARON',
        idproducto: '07002',
        idmonitor: '01',
        folio: 8,
        movimiento: 6,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI ATUN',
        idproducto: '07003',
        idmonitor: '01',
        folio: 8,
        movimiento: 7,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI RIB EYE',
        idproducto: '07004',
        idmonitor: '01',
        folio: 8,
        movimiento: 8,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'EXPERIENCIA OMAKASE YAKUZA',
        idproducto: '08017',
        idmonitor: '01',
        folio: 8,
        movimiento: 9,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'YAKUZA OMAKASE',
        idproducto: '05003',
        idmonitor: '01',
        folio: 20,
        movimiento: 5,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI CAMARON',
        idproducto: '07002',
        idmonitor: '01',
        folio: 20,
        movimiento: 6,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI ATUN',
        idproducto: '07003',
        idmonitor: '01',
        folio: 20,
        movimiento: 7,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI RIB EYE',
        idproducto: '07004',
        idmonitor: '01',
        folio: 20,
        movimiento: 8,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'EXPERIENCIA OMAKASE YAKUZA',
        idproducto: '08017',
        idmonitor: '01',
        folio: 20,
        movimiento: 9,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      
      {
        descripcion: 'YAKUZA OMAKASE',
        idproducto: '05003',
        idmonitor: '01',
        folio: 21,
        movimiento: 5,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI CAMARON',
        idproducto: '07002',
        idmonitor: '01',
        folio: 21,
        movimiento: 6,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI ATUN',
        idproducto: '07003',
        idmonitor: '01',
        folio: 21,
        movimiento: 7,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI RIB EYE',
        idproducto: '07004',
        idmonitor: '01',
        folio: 21,
        movimiento: 8,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'EXPERIENCIA OMAKASE YAKUZA',
        idproducto: '08017',
        idmonitor: '01',
        folio: 21,
        movimiento: 9,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      
      {
        descripcion: 'YAKUZA OMAKASE',
        idproducto: '05003',
        idmonitor: '01',
        folio: 22,
        movimiento: 5,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI CAMARON',
        idproducto: '07002',
        idmonitor: '01',
        folio: 22,
        movimiento: 6,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI ATUN',
        idproducto: '07003',
        idmonitor: '01',
        folio: 22,
        movimiento: 7,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI RIB EYE',
        idproducto: '07004',
        idmonitor: '01',
        folio: 22,
        movimiento: 8,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'EXPERIENCIA OMAKASE YAKUZA',
        idproducto: '08017',
        idmonitor: '01',
        folio: 22,
        movimiento: 9,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      
      {
        descripcion: 'YAKUZA OMAKASE',
        idproducto: '05003',
        idmonitor: '01',
        folio: 23,
        movimiento: 5,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI CAMARON',
        idproducto: '07002',
        idmonitor: '01',
        folio: 23,
        movimiento: 6,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI ATUN',
        idproducto: '07003',
        idmonitor: '01',
        folio: 23,
        movimiento: 7,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI RIB EYE',
        idproducto: '07004',
        idmonitor: '01',
        folio: 23,
        movimiento: 8,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'EXPERIENCIA OMAKASE YAKUZA',
        idproducto: '08017',
        idmonitor: '01',
        folio: 23,
        movimiento: 9,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'YAKUZA OMAKASE',
        idproducto: '05003',
        idmonitor: '01',
        folio: 24,
        movimiento: 5,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI CAMARON',
        idproducto: '07002',
        idmonitor: '01',
        folio: 24,
        movimiento: 6,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI ATUN',
        idproducto: '07003',
        idmonitor: '01',
        folio: 24,
        movimiento: 7,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'TEPANYAKI RIB EYE',
        idproducto: '07004',
        idmonitor: '01',
        folio: 24,
        movimiento: 8,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      },
      {
        descripcion: 'EXPERIENCIA OMAKASE YAKUZA',
        idproducto: '08017',
        idmonitor: '01',
        folio: 24,
        movimiento: 9,
        cantidad: 1.0,
        comentario: '',
        tiempo: '',
        hora: '2026-08-13 09:45:15',
        modificador: false,
        estadomonitor: 0,
        idproductocompuesto: '',
        productocompuestoprincipal: true,
        minutospreparacion: 0.0,
        minutosalerta: 0.0,
        horaproduccion: '',
        cancelado: false,
        prioridad: '',
        enviadomonitor: true,
      }
    ];

    //this.srvComandas.AgregarRegistros(dev);
  }

  onProductoSeleccionado(idProducto: ComandaModel) {
    console.log('Producto seleccionado:', idProducto);
  }
}
